### PR TITLE
fix editor getting unstable when mesh is not valid

### PR DESCRIPTION
**Pull request by murataka**
The editor gets unresponsive and sometimes crashes , even when the skeletal mesh is set but it is replaced by a child skeletal mesh component class in blueprints.

### CODE REVIEW

**Comment by Sixze** [comment]
Looks like there is something wrong on your end. In a normal situation the mesh component should never be null, you can replace it with another component from C++ or blueprints, but you can't remove it easily.

If it turns out that the mesh component is indeed null, I can advise you to check that the component class really exists, that the `FObjectInitializer::DoNotCreateDefaultSubobject()` function is not used, and that the plugin that contains the component is enabled.

I have added my own version of the fix, but I advise you to figure out what the real root cause of this issue is.

**Comment by murataka** [comment]
The mesh component is temporarely null when you change the component from skeletalmesh component to budget skeletalmesh component. without that fix , it is impossible to use animation budget by changing it to skeletal mesh component budgeted, as the editor crashes.

**Comment by Sixze** [comment]
Weird, I didn't encounter any issues while testing this. Perhaps this issue only affects older versions of UE?

**Comment by murataka** [comment]
will test with new version soon , thanks for the update ! good job man ...

**Pull request closed without merging**
